name: yakushiin_player
description: "YakushiinPlayer By Luckykeeper"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  adaptive_theme: ^3.7.0
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_riverpod: ^2.6.1
  flutter_smart_dialog: ^4.9.8+7
  logger: ^2.5.0
  media_kit: ^1.2.0
  media_kit_libs_video: ^1.0.6
  media_kit_video: ^1.3.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  window_manager: ^0.4.3
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.5
  hive_ce: any
  hive_ce_flutter: any
  dio: ^5.8.0+1
  wakelock_plus: ^1.2.11
  flutter_volume_controller: ^1.3.3
  pedometer: ^4.0.2
  geolocator: ^13.0.3
  weather: ^3.1.1
  geolocator_android: ^4.6.2
  geolocator_web: ^4.1.2
  geolocator_apple: ^2.3.13
  geolocator_windows: ^0.2.5
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  hive_ce_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/Yakushiin-fit-0.75x.png
    - assets/images/operationFailedYakushiin.jpg
    - assets/images/operationSuccessYakushiin.jpg
    - assets/images/splash.png
    - assets/images/lockup_flutter_horizontal.png

  fonts:
    # - family: LXGWWenKai
    #   fonts:
    #     - asset: lib/theme/fonts/LXGWWenKai/LXGWWenKai-Medium.ttf
    #       weight: 500
    #     - asset: lib/theme/fonts/LXGWWenKai/LXGWWenKai-Regular.ttf
    #       weight: 400
    #     - asset: lib/theme/fonts/LXGWWenKai/LXGWWenKai-Light.ttf
    #       weight: 300
    - family: simkai
      fonts:
        - asset: lib/theme/fonts/simkai.ttf
        
flutter_native_splash:
  color: "#79c4be"
  image: assets/images/splash.png
  branding: assets/images/lockup_flutter_horizontal.png
  android_12:
    color: "#79c4be"
    image: assets/images/splash.png
    branding: assets/images/lockup_flutter_horizontal.png