// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:yakushiin_player/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GatewaySettingAdapter());
    registerAdapter(NoaPlayerV2MusicAdapter());
    registerAdapter(NoaPlayerV2PlayListAdapter());
  }
}
